import React from 'react';
import { SWRProvider } from '@/libs/swr';
import { CssBaseline } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <React.Fragment>
      <CssBaseline />
      <html lang="en">
        <head>
          <meta
            name="viewport"
            content="initial-scale=1, width=device-width, maximum-scale=1.0, user-scalable=no"
          />
          <title>redubai</title>
        </head>
        <body>
          <SWRProvider>{children}</SWRProvider>
        </body>
      </html>
    </React.Fragment>
  );
}
